package ru.aberezhnoy.common.domain;

public enum CommandType {

    DOWNLOAD, LOGIN, UPLOAD, READY_TO_UPLOAD, UPLOAD_FINISHED, FILES_LIST, READY_TO_DOWNLOAD,
    READY_TO_RECEIVE, FINISHED_DOWNLOAD, LOGIN_OK, CLOUD_FILES_LIST, REGISTRATION_FAILED
}
